title: Rondleiding door MakeCode
hero_image: images/banner.png
description: standaard-project-sjabloon beschrijving
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Rondleiding door MakeCode
