title: Visite guidée de MakeCode
hero_image: images/banner.png
description: description modele-projet-par defaut
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Visite guidée de MakeCode
